# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CleanStore' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'BaseViewSwift'
  pod 'Firebase/Core'
  pod 'FacebookCore', :git => 'https://github.com/facebook/facebook-sdk-swift'
  pod 'FacebookLogin', :git => 'https://github.com/facebook/facebook-sdk-swift'
  pod 'FacebookShare', :git => 'https://github.com/facebook/facebook-sdk-swift'
  pod 'SkyFloatingLabelTextField', '~> 3.0'


  # Pods for CleanStore

  target 'CleanStoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CleanStoreUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
